name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  emojiweb:
    runs-on: ubuntu-latest
    concurrency: deploy-emojiweb
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
