name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.*"
      - "Dockerfile*"
      - "emojiname/**/*.json"
      - "live/fly.toml"
jobs:
  huntlive:
    runs-on: ubuntu-latest
    concurrency: deploy-huntlive
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config live/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
